// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lookupFeedByUrl.sql

package database

import (
	"context"
)

const lookUpFeedByUrl = `-- name: LookUpFeedByUrl :one

SELECT id, name, url, user_id, created_at, updated_at, last_fetched_at FROM feeds
WHERE url = $1
`

func (q *Queries) LookUpFeedByUrl(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, lookUpFeedByUrl, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastFetchedAt,
	)
	return i, err
}
